export const events = [
  {
    title: "Next.js Conf 2026",
    image: "/images/event1.png",
    slug: "nextjs-conf-2026",
    location: "San Francisco, CA",
    date: "Oct 24, 2026",
    time: "09:00 AM",
  },
  {
    title: "React Summit 2026",
    image: "/images/event2.png",
    slug: "react-summit-2026",
    location: "Amsterdam, Netherlands",
    date: "Jun 12, 2026",
    time: "10:00 AM",
  },
  {
    title: "Web Summit 2026",
    image: "/images/event3.png",
    slug: "web-summit-2026",
    location: "Lisbon, Portugal",
    date: "Nov 11, 2026",
    time: "09:00 AM",
  },
  {
    title: "JS World Conference",
    image: "/images/event4.png",
    slug: "js-world-2026",
    location: "Online / Amsterdam",
    date: "Feb 15, 2027",
    time: "08:30 AM",
  },
  {
    title: "Google I/O 2026",
    image: "/images/event5.png",
    slug: "google-io-2026",
    location: "Mountain View, CA",
    date: "May 20, 2026",
    time: "10:00 AM",
  },
  {
    title: "AWS re:Invent 2026",
    image: "/images/event6.png",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, NV",
    date: "Nov 30, 2026",
    time: "09:00 AM",
  },
];
